Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: go1.x
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        API_ENV: !Ref APIEnv

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prod
    Description: "Enter the stage name: dev, hml, or prod. Default is dev."
  APIEnv:
    Type: String
    Default: online
    AllowedValues:
      - local
      - online
    Description: "Enter the API env: local or online. Default is online(aws), local is used during tests."

Resources:
