version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tutor-pet-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t4ktp4u6p2cd"
s3_prefix = "tutor-pet-api"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
